### ISSUE TITLE
when i run the code in eclipse,it seems an error ocurred.

### ISSUE THREAD

**Issue by hjw541988478** [frogermcs/InstaMaterial#14]
Caused by: java.lang.NullPointerException
at io.github.froger.instamaterial.ui.activity.MainActivity.setupFeed(MainActivity.java:60)
at io.github.froger.instamaterial.ui.activity.MainActivity.onCreate(MainActivity.java:44)

**Comment by hjw541988478** [comment]
rvFeed.setLayoutManager(linearLayoutManager);
it seesm that this line reported nullpointerexception.

**Comment by danyhaddad** [comment]
did you find any solution?

**Comment by hjw541988478** [comment]
i have changed my ide to androidstudio,and everything goes allright.

**Comment by Dedy54** [comment]
how if i run in eclipse guys?

**Comment by Dedy54** [comment]
plis help me

**Comment by hjw541988478** [comment]
@Dedy54 dont know why,but i think you should change your ide to android studio.It works great.
