### ISSUE TITLE
drawer_menu actions

### ISSUE THREAD

**Issue by Leoz83** [frogermcs/InstaMaterial#20]
Hi, how i can add actions on click some elements into drawer menu?

Thanks

**Comment by Leoz83** [comment]
this in BaseActivity have worked for me
```
protected void setupToolbar() {
    if (toolbar != null) {
        setSupportActionBar(toolbar);
        toolbar.setNavigationIcon(R.drawable.ic_menu_white);

        navigationView.setNavigationItemSelectedListener(
            new NavigationView.OnNavigationItemSelectedListener() {
                @Override
                public boolean onNavigationItemSelected(MenuItem menuItem) {
                    int position = -1;
                    switch (menuItem.getItemId()) {
                        case R.id.menu_foo_1:
                            #
                        break;
                    }
                    drawerLayout.closeDrawer(Gravity.LEFT);



                    return false;
                }
            });


}
}
```

**Comment by tinasherobert** [comment]
**Note **, Replace this on BaseDrawerActivity 

<pre>@Override
    protected void setupToolbar() {
        super.setupToolbar();
        if (getToolbar() != null) {
            getToolbar().setNavigationOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    drawerLayout.openDrawer(Gravity.LEFT);
                }
            });
            vNavigation.setNavigationItemSelectedListener(
                    new NavigationView.OnNavigationItemSelectedListener() {
                        @Override
                        public boolean onNavigationItemSelected(MenuItem menuItem) {
                            int position = -1;
                            switch (menuItem.getItemId()) {
                                case R.id.news_feed:
                                    Snackbar.make(getCurrentFocus(), "Clicked!", Snackbar.LENGTH_SHORT).show();
                                    
                                    break;
                            }
                            drawerLayout.closeDrawer(Gravity.LEFT);

                            return false;
                        }
                    });

        }
    }</pre>

**Comment by gdaelexxer** [comment]
thank you let me do that
