### ISSUE TITLE
I discovered a bug in feed animation

### ISSUE THREAD

**Issue by hishamBakr** [frogermcs/InstaMaterial#4]
I discovered a bug in feed animation: if you set visibility to gone on the square image view,you will find animation just happen to first feed

this is not discovered in current implementation cause first feed take the whole screen

I did that cause I need to simulate feeds that dont have image or image that its height is less than screen height

**Comment by hishamBakr** [comment]
I fixed it by these modifications:
 private static final int ANIMATED_ITEMS_COUNT = 5; // 5 instead of 2


// added dynamic starting delay
   private void runEnterAnimation(View view, int position) {
        if (position >= ANIMATED_ITEMS_COUNT - 1) {
            return;
        }

        if (position > lastAnimatedPosition) {
            lastAnimatedPosition = position;
           view.setTranslationY(Utils.getScreenHeight(context));
            view.animate()
                    .translationY(0)
                    .setInterpolator(new DecelerateInterpolator(3.f))
                    .setDuration(700).setStartDelay(position*200)
                    .start();

        }
    }

**Comment by frogermcs** [comment]
This is only example code. So probably in production app you will have to prepare more "dynamic" solution for calculating visible items. But anyway thank you for your suggestion. :+1:
